Repository ProvableHQ/leo, pull requests merged in 2021-05, with the labels that each got.

#549 [RFC] Leo RFC proposal
  docs/rfc/000-rfc-format.md
  docs/rfc/__template.md
Labels: documentation, help wanted

#912 Bug 909 Fix const vars not enforced
  asg/src/error/mod.rs
  asg/src/statement/definition.rs
  asg/tests/pass/address/ternary.leo
  asg/tests/pass/boolean/not_mutable.leo
  asg/tests/pass/circuits/pedersen_mock.leo
  asg/tests/pass/core/blake2s_random.leo
  asg/tests/pass/field/ternary.leo
  asg/tests/pass/group/point_input.leo
  asg/tests/pass/group/ternary.leo
  asg/tests/pass/integers/i128/ternary.leo
  asg/tests/pass/integers/i16/ternary.leo
  asg/tests/pass/integers/i32/ternary.leo
  asg/tests/pass/integers/i64/ternary.leo
  asg/tests/pass/integers/i8/ternary.leo
  asg/tests/pass/integers/u128/ternary.leo
  asg/tests/pass/integers/u16/ternary.leo
  asg/tests/pass/integers/u32/ternary.leo
  asg/tests/pass/integers/u64/ternary.leo
  asg/tests/pass/integers/u8/ternary.leo
  asg/tests/pass/mutability/let_mut_nested.leo
  asg/tests/pass/mutability/swap.leo
  asg/tests/pass/statements/conditional/for_loop.leo
  asg/tests/pass/statements/ternary_basic.leo
  compiler/tests/address/ternary.leo
  compiler/tests/boolean/not_mutable.leo
  compiler/tests/circuits/pedersen_mock.leo
  compiler/tests/core/packages/unstable/blake2s/blake2s_random.leo
  compiler/tests/integers/i128/ternary.leo
  compiler/tests/integers/i16/ternary.leo
  compiler/tests/integers/i32/ternary.leo
  compiler/tests/integers/i64/ternary.leo
  compiler/tests/integers/i8/ternary.leo
  compiler/tests/integers/u128/ternary.leo
  compiler/tests/integers/u16/ternary.leo
  compiler/tests/integers/u32/ternary.leo
  compiler/tests/integers/u64/ternary.leo
  compiler/tests/integers/u8/ternary.leo
  compiler/tests/mutability/let_mut_nested.leo
  compiler/tests/mutability/swap.leo
  compiler/tests/statements/conditional/for_loop.leo
  compiler/tests/statements/mod.rs
  compiler/tests/statements/ternary_basic.leo
  compiler/tests/statements/ternary_non_const_conditional_fail.leo
Labels: bug

#922 RFC Todos
  docs/rfc/001-initial-strings.md
Labels: Design

#926 [RFC Strings] Adds code samples to strings RFC
  docs/rfc/001-initial-strings.md
Labels: RFC

#923 Import Bug Fixes
  asg/src/program/mod.rs
  ast/src/imports/package_access.rs
  grammar/README.md
  grammar/abnf-grammar.txt
  parser/src/errors/syntax.rs
  parser/src/parser/file.rs
  tests/expectations/parser/parser/import/import_empty_list_fail.leo.out
  tests/expectations/parser/parser/import/many_import_star.leo.out
  tests/expectations/parser/parser/import/star.leo.out
  tests/parser/import/import_empty_list_fail.leo
Labels: abnf, bug

#979 Feature/string canonicalization
  ast/src/reducer/canonicalization.rs
  ast/src/reducer/reconstructing_director.rs
  ast/src/reducer/reconstructing_reducer.rs
  compiler/src/phases/reducing_director.rs
  compiler/src/value/value.rs
  compiler/tests/canonicalization/mod.rs
  compiler/tests/canonicalization/string_transformation.json
  compiler/tests/canonicalization/string_transformation.leo
  compiler/tests/type_inference/basic.json
  compiler/tests/type_inference/basic.leo
  input/src/leo-input.pest
  parser/src/tokenizer/lexer.rs
  tests/compiler/global_consts/global_const_types.leo
  tests/compiler/string/circuit.leo
  tests/compiler/string/equality.leo
  tests/compiler/string/inputs/string.in
  tests/compiler/string/inputs/string_out.in
  tests/expectations/compiler/compiler/string/circuit.leo.out
  tests/expectations/compiler/compiler/string/equality.leo.out
Labels: Implementation
