Repository ProvableHQ/leo, pull requests merged in 2021-07, with the labels that each got.

#1056 [RFC] Add initial RFC for type casts.
  docs/rfc/004-integer-type-casts.md
Labels: RFC

#1072 [RFC] Extending scope of the RFC to include proving system and curve
  docs/rfc/003-imports-stabilization.md
Labels: RFC

#1093 Array Indexing Fixes
  ast/src/errors/combiner.rs
  ast/src/reducer/canonicalization.rs
  compiler/src/statement/assign/assignee/array_index.rs
  compiler/src/statement/assign/assignee/array_range_index.rs
  compiler/tests/canonicalization/compound_assignment.json
  compiler/tests/canonicalization/compound_assignment.leo
  tests/compiler/array/complex_access.leo
  tests/compiler/array/input/complex_access.in
  tests/expectations/compiler/compiler/array/complex_access.leo.out
Labels: bug-fix

#1113 Feature/circuit constant value
  .github/workflows/ci.yml
  asg-passes/src/constant_folding/mod.rs
  asg/src/const_value.rs
  asg/src/expression/array_access.rs
  asg/src/expression/array_init.rs
  asg/src/expression/array_inline.rs
  asg/src/expression/array_range_access.rs
  asg/src/expression/circuit_access.rs
  asg/src/expression/circuit_init.rs
  asg/src/expression/constant.rs
  asg/src/expression/mod.rs
  asg/src/expression/ternary.rs
  asg/src/expression/tuple_access.rs
  asg/src/expression/tuple_init.rs
  asg/src/expression/variable_ref.rs
  compiler/src/expression/expression.rs
  tests/compiler/array/complex_access.leo
Labels: Implementation, bug-fix

#1117 [RFC] Update the type casts RFC.
  docs/rfc/004-integer-type-casts.md
Labels: RFC

#1067 [RFC] Adds countdown loops RFC
  docs/rfc/005-countdown-loops.md
Labels: RFC

#1165 [Feature] Patch abnf to 0.12.0, return leo-abnf crate
  Cargo.lock
  grammar/Cargo.toml
  grammar/src/main.rs
Labels: dependencies

#1169 [Bugfix] Fixes Rust Error for Invalid Slice
  asg/src/expression/array_range_access.rs
  tests/compiler/array/array_range_access_fail.leo
  tests/compiler/array/input/array_range_access_fail.in
  tests/expectations/compiler/compiler/array/array_range_access_fail.leo.out
Labels: bug-fix

#1172 [RFC] Update import stabilization RFC to follow changes
  docs/rfc/003-imports-stabilization.md
Labels: RFC

#1178 [Bugfix] Remove Format Strings and Fix ABNF Console Statements
  FORMAT_ABNF_GRAMMER.md
  asg/src/checks/return_path.rs
  asg/src/const_value.rs
  asg/src/reducer/monoidal_director.rs
  asg/src/reducer/monoidal_reducer.rs
  asg/src/reducer/reconstructing_director.rs
  asg/src/reducer/reconstructing_reducer.rs
  asg/src/reducer/visitor.rs
  asg/src/reducer/visitor_director.rs
  asg/src/statement/console.rs
  asg/tests/fail/console/log_parameter_fail_empty.leo
  asg/tests/fail/console/log_parameter_fail_none.leo
  asg/tests/fail/console/mod.rs
  ast/README.md
  ast/src/errors/reducer.rs
  ast/src/reducer/canonicalization.rs
  ast/src/reducer/reconstructing_director.rs
  ast/src/statements/console/console_args.rs
  ast/src/statements/console/console_function.rs
  ast/src/statements/console/formatted_string.rs
  ast/src/statements/console/mod.rs
  compiler/src/console/format.rs
  compiler/src/errors/console.rs
  compiler/src/phases/reducing_director.rs
  grammar/.gitattributes
  grammar/FORMAT_ABNF_GRAMMER.md
  grammar/README.md
  grammar/abnf-grammar.txt
  grammar/format-abnf-grammar.txt
  grammar/src/main.rs
  parser/README.md
  parser/src/parser/statement.rs
  parser/src/tokenizer/lexer.rs
  parser/src/tokenizer/token.rs
  tests/expectations/compiler/compiler/char/nonprinting.leo.out
  tests/expectations/compiler/compiler/char/out.leo.out
  tests/expectations/compiler/compiler/console/debug.leo.out
  tests/expectations/compiler/compiler/console/error.leo.out
  tests/expectations/compiler/compiler/console/log.leo.out
  tests/expectations/compiler/compiler/console/log_conditional.leo.out
  tests/expectations/compiler/compiler/console/log_input.leo.out
  tests/expectations/compiler/compiler/console/log_parameter.leo.out
  tests/expectations/compiler/compiler/console/log_parameter_fail_empty.leo.out
  tests/expectations/compiler/compiler/console/log_parameter_fail_none.leo.out
  tests/expectations/compiler/compiler/console/log_parameter_many.leo.out
  tests/expectations/compiler/compiler/input_files/program_input/main_group.leo.out
  tests/expectations/compiler/compiler/input_files/program_input/main_multi_dimension_array.leo.out
  tests/expectations/compiler/compiler/input_files/program_input_constants/main_array.leo.out
  tests/expectations/compiler/compiler/input_files/program_input_constants/main_group.leo.out
  tests/expectations/parser/parser/expression/literal/string.leo.out
  tests/expectations/parser/parser/expression/literal/string_fail.leo.out
  tests/expectations/parser/parser/statement/console.leo.out
  tests/parser/expression/literal/string.leo
  tests/parser/expression/literal/string_fail.leo
Labels: Implementation, bug-fix

#1182 [Bugfix] canonicalize imports
  asg/src/error/mod.rs
  imports/src/errors/import_parser.rs
  imports/src/parser/parse_symbol.rs
  tests/compiler/import/imports/lib.leo
  tests/compiler/import/string_import.leo
Labels: bug-fix

#1166 [RFC] Initial draft for array types with unspecified size.
  docs/rfc/006-arrays-without-size.md
Labels: RFC

#1185 [Bugfix] Ternary Type Check
  asg/src/error/mod.rs
  asg/src/expression/ternary.rs
  tests/compiler/statements/assign_ternary.leo
  tests/expectations/compiler/compiler/statements/assign_ternary.leo.out
Labels: bug-fix

#1203 [Bugfix] Variable Shadowing
  asg/src/error/mod.rs
  asg/src/statement/definition.rs
  grammar/FORMAT_ABNF_GRAMMAR.md
  tests/compiler/function/duplicate_definition_fail.leo
  tests/compiler/statements/duplicate_variable.leo
  tests/expectations/compiler/compiler/function/duplicate_definition_fail.leo.out
  tests/expectations/compiler/compiler/statements/duplicate_variable.leo.out
Labels: bug-fix

#1201 [Feature Implmentation] Stderr and debug remove
  asg/src/reducer/monoidal_director.rs
  asg/src/reducer/reconstructing_director.rs
  asg/src/reducer/reconstructing_reducer.rs
  asg/src/reducer/visitor_director.rs
  asg/src/statement/console.rs
  asg/tests/pass/console/debug.leo
  asg/tests/pass/console/mod.rs
  ast/src/errors/error.rs
  ast/src/reducer/canonicalization.rs
  ast/src/reducer/reconstructing_director.rs
  ast/src/statements/console/console_function.rs
  compiler/src/console/console.rs
  compiler/src/phases/reducing_director.rs
  leo/logger.rs
  leo/main.rs
  parser/src/parser/statement.rs
  parser/src/test.rs
  tests/compiler/console/debug.leo
  tests/expectations/compiler/compiler/array/variable_slice_fail.leo.out
  tests/expectations/compiler/compiler/core/core_circuit_star_fail.leo.out
  tests/expectations/compiler/compiler/core/core_package_invalid.leo.out
  tests/expectations/compiler/compiler/core/core_unstable_package_invalid.leo.out
  tests/expectations/compiler/compiler/function/duplicate_definition_fail.leo.out
  tests/expectations/compiler/compiler/function/multiple_returns_fail.leo.out
  tests/expectations/compiler/compiler/function/multiple_returns_fail_conditional.leo.out
  tests/expectations/compiler/compiler/input_files/program_registers/registers_fail.leo.out
  tests/expectations/parser/parser/statement/console.leo.out
  tests/parser/statement/console.leo
Labels: Implementation

#1208 [Bugfix]Fix recently merged tests failing
  compiler/src/test.rs
  parser/src/test.rs
  tests/compiler/function/duplicate_definition_fail.leo
  tests/expectations/compiler/compiler/function/duplicate_definition_fail.leo.out
Labels: bug-fix
