Repository ProvableHQ/leo, pull requests merged in 2021-08, with the labels that each got.

#1225 [Fix] Adds Self canonicalization for static calls
  asg/src/const_value.rs
  asg/src/expression/constant.rs
  asg/src/expression/mod.rs
  asg/src/program/function.rs
  asg/src/program/mod.rs
  asg/src/reducer/monoidal_director.rs
  asg/src/statement/assign.rs
  asg/src/statement/block.rs
  asg/src/statement/definition.rs
  ast/src/reducer/canonicalization.rs
  ast/src/reducer/reconstructing_director.rs
  ast/src/types/type_.rs
  compiler/src/compiler.rs
  compiler/src/constraints/constraints.rs
  compiler/src/expression/array/access.rs
  compiler/src/expression/function/function.rs
  compiler/src/function/input/main_function_input.rs
  compiler/src/function/main_function.rs
  compiler/src/function/result/result.rs
  compiler/src/phases/reducing_director.rs
  compiler/src/statement/assign/assignee/array_index.rs
  compiler/src/statement/conditional/conditional.rs
  compiler/src/value/value.rs
  imports/src/parser/parse_symbol.rs
  input/src/errors/parser.rs
  input/src/values/group_coordinate.rs
  input/src/values/value.rs
  leo/config.rs
  leo/updater.rs
  package/src/package.rs
  parser/examples/parser.rs
  parser/src/parser/file.rs
  parser/src/parser/statement.rs
  parser/src/tokenizer/lexer.rs
  tests/expectations/compiler/compiler/circuits/member_static_function_nested.leo.out
Labels: bug-fix

#1235 [Feature] Getting import tests back
  compiler/src/test.rs
  tests/compiler/import_dependency/imports/dependency/inputs/dependency.in
  tests/compiler/import_dependency/imports/dependency/src/main.leo
  tests/compiler/import_dependency/input/dummy.in
  tests/compiler/import_dependency/readme.md
  tests/compiler/import_dependency/tests/import_dependency_folder.leo
  tests/compiler/import_local/import_all.leo
  tests/compiler/import_local/import_as.leo
  tests/compiler/import_local/import_dir.leo
  tests/compiler/import_local/import_files.leo
  tests/compiler/import_local/import_many.leo
  tests/compiler/import_local/import_weird_names.leo
  tests/compiler/import_local/input/dummy.in
  tests/compiler/import_local/local_imports/a-9.leo
  tests/compiler/import_local/local_imports/circuits.leo
  tests/compiler/import_local/local_imports/lib.leo
  tests/compiler/import_local/local_imports/nested/hello.leo
  tests/compiler/import_old/alias.leo
  tests/compiler/import_old/basic.leo
  tests/compiler/import_old/imports/a-9.leo
  tests/compiler/import_old/imports/a0-f.leo
  tests/compiler/import_old/imports/bar/.gitignore
  tests/compiler/import_old/imports/bar/Leo.toml
  tests/compiler/import_old/imports/bar/src/bat/bat.leo
  tests/compiler/import_old/imports/bar/src/baz.leo
  tests/compiler/import_old/imports/bar/src/lib.leo
  tests/compiler/import_old/imports/car/.gitignore
  tests/compiler/import_old/imports/car/Leo.toml
  tests/compiler/import_old/imports/car/src/lib.leo
  tests/compiler/import_old/imports/hello-world.leo
  tests/compiler/import_old/imports/lib.leo
  tests/compiler/import_old/imports/test-import.leo
  tests/compiler/import_old/input/dummy.in
  tests/compiler/import_old/many_import.leo
  tests/compiler/import_old/many_import_star.leo
  tests/compiler/import_old/multiple.leo
  tests/compiler/import_old/names.leo
  tests/compiler/import_old/names_a_dash_fail.leo
  tests/compiler/import_old/names_dash_a_fail.leo
  tests/compiler/import_old/names_dollar_fail.leo
  tests/compiler/import_old/names_underscore_fail.leo
  tests/compiler/import_old/star.leo
  tests/compiler/import_old/star_fail.leo
  tests/compiler/import_old/string_import.leo
  tests/expectations/compiler/compiler/import_dependency/tests/import_dependency_folder.leo.out
  tests/expectations/compiler/compiler/import_local/import_all.leo.out
  tests/expectations/compiler/compiler/import_local/import_as.leo.out
  tests/expectations/compiler/compiler/import_local/import_dir.leo.out
  tests/expectations/compiler/compiler/import_local/import_files.leo.out
  tests/expectations/compiler/compiler/import_local/import_many.leo.out
  tests/expectations/compiler/compiler/import_local/import_weird_names.leo.out
Labels: Implementation

#1241 [Feature] Adds compiler phases pdf
  docs/compiler-phases.pdf
Labels: documentation

#1240 [Feature] Allow dashes in member access
  parser/src/parser/file.rs
  tests/compiler/import_local/import_weird_names_nested.leo
  tests/compiler/import_local/local_imports/nested/c-d.leo
  tests/expectations/compiler/compiler/import_local/import_weird_names_nested.leo.out
Labels: bug-fix

#1266 [Fix] Recursive imports
  imports/src/parser/import_parser.rs
Labels: bug-fix

#1270 [Feature] Removes AST snapshots on leo clean
  errors/src/package/package_errors.rs
  leo/commands/clean.rs
  package/src/outputs/ast_snapshot.rs
  package/src/outputs/mod.rs
Labels: Implementation

#1119 [Feature] Imports Stabilization
  .circleci/config.yml
  .circleci/r
  Cargo.lock
  Cargo.toml
  compiler/src/compiler.rs
  compiler/src/option.rs
  compiler/src/test.rs
  errors/src/cli/cli_errors.rs
  errors/src/package/package_errors.rs
  imports/src/parser/import_parser.rs
  imports/src/parser/parse_package.rs
  leo/commands/build.rs
  leo/commands/package/add.rs
  leo/commands/package/fetch.rs
  leo/commands/package/mod.rs
  leo/commands/package/remove.rs
  leo/commands/test.rs
  leo/context.rs
  leo/main.rs
  package/Cargo.toml
  package/README.md
  package/src/root/lock_file.rs
  package/src/root/manifest.rs
  package/src/root/mod.rs
  package/src/root/zip.rs
Labels: help wanted, Implementation, developer-experience

#1260 [CI] ACL2 tgc CI
  .github/workflows/acl2.yml
  Cargo.lock
  FORMAT_ABNF_GRAMMER.md
  ast/src/reducer/canonicalization.rs
  test-framework/.gitignore
  test-framework/Cargo.toml
  test-framework/src/bin/tgc.rs
  test-framework/src/test.rs
Labels: Implementation, ci

#1267 [Bugfix] Ternary Implicit and Explicit Unkown Type
  asg/src/expression/ternary.rs
  tests/compiler/statements/inputs/ternary_explicit_and_implicit.in
  tests/compiler/statements/ternary_explicit_and_implicit.leo
  tests/expectations/compiler/compiler/statements/assign_ternary.leo.out
  tests/expectations/compiler/compiler/statements/ternary_explicit_and_implicit.leo.out
Labels: bug-fix

#1272 [Implmentation] Adds Type to Circuit Member Access Expressions
  asg/src/expression/call.rs
  asg/src/expression/circuit_access.rs
  asg/src/statement/mod.rs
  ast/src/expression/circuit_member_access.rs
  ast/src/reducer/canonicalization.rs
  ast/src/reducer/reconstructing_director.rs
  ast/src/reducer/reconstructing_reducer.rs
  compiler/src/phases/reducing_director.rs
  parser/src/parser/expression.rs
  tests/expectations/compiler/compiler/array/complex_access.leo.out
  tests/expectations/compiler/compiler/array/registers.leo.out
  tests/expectations/compiler/compiler/char/circuit.leo.out
  tests/expectations/compiler/compiler/circuits/big_self_in_circuit_replacement.leo.out
  tests/expectations/compiler/compiler/circuits/const_self_variable.leo.out
  tests/expectations/compiler/compiler/circuits/define_circuit_inside_circuit_function.leo.out
  tests/expectations/compiler/compiler/circuits/inline.leo.out
  tests/expectations/compiler/compiler/circuits/inline_member_pass.leo.out
  tests/expectations/compiler/compiler/circuits/member_function.leo.out
  tests/expectations/compiler/compiler/circuits/member_function_nested.leo.out
  tests/expectations/compiler/compiler/circuits/member_variable.leo.out
  tests/expectations/compiler/compiler/circuits/member_variable_and_function.leo.out
  tests/expectations/compiler/compiler/circuits/mut_self_variable.leo.out
  tests/expectations/compiler/compiler/circuits/mut_self_variable_branch.leo.out
  tests/expectations/compiler/compiler/circuits/mut_self_variable_conditional.leo.out
  tests/expectations/compiler/compiler/circuits/mut_variable.leo.out
  tests/expectations/compiler/compiler/circuits/mutable_call_immutable_context.leo.out
  tests/expectations/compiler/compiler/circuits/pedersen_mock.leo.out
  tests/expectations/compiler/compiler/circuits/self_member.leo.out
  tests/expectations/compiler/compiler/function/multiple_returns_main.leo.out
  tests/expectations/compiler/compiler/global_consts/global_const_types.leo.out
  tests/expectations/compiler/compiler/input_files/program_input_and_program_state/basic.leo.out
  tests/expectations/compiler/compiler/input_files/program_input_and_program_state/token_withdraw.leo.out
  tests/expectations/compiler/compiler/input_files/program_state/access_all.leo.out
  tests/expectations/compiler/compiler/input_files/program_state/access_state.leo.out
  tests/expectations/compiler/compiler/mutability/circuit_function_mut.leo.out
  tests/expectations/compiler/compiler/mutability/circuit_variable_mut.leo.out
  tests/expectations/compiler/compiler/statements/compound_assignment.leo.out
  tests/expectations/compiler/compiler/string/circuit.leo.out
  tests/expectations/parser/parser/expression/access/array_range_access.leo.out
  tests/expectations/parser/parser/expression/access/circuit.leo.out
  tests/expectations/parser/parser/expression/unary/negate.leo.out
  tests/expectations/parser/parser/expression/unary/not.leo.out
Labels: Implementation
