Repository ProvableHQ/leo, pull requests merged in 2021-04, with the labels that each got.

#816 Unused code removal + improving coverage
  Cargo.lock
  ast/src/common/array_dimensions.rs
  compiler/Cargo.toml
  compiler/src/errors/compiler.rs
  compiler/src/errors/expression.rs
  compiler/src/errors/function.rs
  compiler/src/errors/import.rs
  compiler/src/errors/output_file.rs
  compiler/src/errors/statement.rs
  compiler/src/errors/value/address.rs
  compiler/src/errors/value/field.rs
  compiler/src/errors/value/integer.rs
  compiler/src/errors/value/value.rs
  compiler/src/output/output_file.rs
  imports/src/errors/import_parser.rs
  package/src/errors/imports/directory.rs
  package/src/errors/inputs/directory.rs
  package/src/errors/inputs/input.rs
  package/src/errors/inputs/state.rs
  package/src/errors/outputs/checksum.rs
  package/src/errors/outputs/circuit.rs
  package/src/errors/outputs/directory.rs
  package/src/errors/outputs/proof.rs
  package/src/errors/outputs/proving_key.rs
  package/src/errors/outputs/verification_key.rs
  package/src/errors/package.rs
  package/src/errors/root/gitignore.rs
  package/src/errors/root/readme.rs
  package/src/errors/root/zip.rs
  package/src/errors/source/lib.rs
  package/src/errors/source/main.rs
  package/src/imports/directory.rs
Labels: refactor

#824 Feature/no space between literals
  compiler/tests/field/mod.rs
  compiler/tests/field/no_space_between_literal.leo
  compiler/tests/group/mod.rs
  compiler/tests/group/no_space_between_literal.leo
  compiler/tests/integers/i128/mod.rs
  compiler/tests/integers/i128/no_space_between_literal.leo
  compiler/tests/integers/i16/mod.rs
  compiler/tests/integers/i16/no_space_between_literal.leo
  compiler/tests/integers/i32/mod.rs
  compiler/tests/integers/i32/no_space_between_literal.leo
  compiler/tests/integers/i64/mod.rs
  compiler/tests/integers/i64/no_space_between_literal.leo
  compiler/tests/integers/i8/mod.rs
  compiler/tests/integers/i8/no_space_between_literal.leo
  compiler/tests/integers/u128/mod.rs
  compiler/tests/integers/u128/no_space_between_literal.leo
  compiler/tests/integers/u16/mod.rs
  compiler/tests/integers/u16/no_space_between_literal.leo
  compiler/tests/integers/u32/mod.rs
  compiler/tests/integers/u32/no_space_between_literal.leo
  compiler/tests/integers/u64/mod.rs
  compiler/tests/integers/u64/no_space_between_literal.leo
  compiler/tests/integers/u8/mod.rs
  compiler/tests/integers/u8/no_space_between_literal.leo
  grammar/abnf-grammar.md
  grammar/abnf-grammar.txt
  parser/src/parser/context.rs
  parser/src/parser/expression.rs
  parser/src/parser/file.rs
  parser/src/parser/mod.rs
Labels: abnf, developer-experience, documentation

#825 Bug/815 mutable method imuttable context
  asg/src/expression/circuit_init.rs
  compiler/tests/circuits/mod.rs
  compiler/tests/circuits/mutable_call_immutable_context.leo
Labels: abnf, bug

#835 [ABNF] Improve the documentation of the grammar and fix a rule
  grammar/abnf-grammar.md
  grammar/abnf-grammar.txt
Labels: abnf, documentation

#837 Adds error when function defined more than once
  asg/src/error/mod.rs
  asg/src/program/mod.rs
  compiler/tests/function/duplicate_definition.leo
  compiler/tests/function/mod.rs
Labels: bug

#838 Fix package name checks
  package/src/package.rs
Labels: developer-experience, refactor

#814 [CLI] Adds --path argument to Leo CLI
  .circleci/leo-add-remove.sh
  .circleci/leo-init.sh
  leo/commands/build.rs
  leo/commands/clean.rs
  leo/commands/deploy.rs
  leo/commands/init.rs
  leo/commands/lint.rs
  leo/commands/mod.rs
  leo/commands/new.rs
  leo/commands/package/add.rs
  leo/commands/package/clone.rs
  leo/commands/package/login.rs
  leo/commands/package/logout.rs
  leo/commands/package/publish.rs
  leo/commands/package/remove.rs
  leo/commands/prove.rs
  leo/commands/run.rs
  leo/commands/setup.rs
  leo/commands/test.rs
  leo/commands/update.rs
  leo/commands/watch.rs
  leo/main.rs
Labels: feature, help wanted, update-docs

#853 Reversed-Accesses
  ast/src/reducer/canonicalization.rs
  compiler/tests/canonicalization/compound_assignment.json
  compiler/tests/canonicalization/compound_assignment.leo
Labels: bug

#860 [CLI] Adds colors to Windows cmd
  Cargo.lock
  Cargo.toml
  leo/logger.rs
Labels: bug, developer-experience

#861 [CLI] Fixes issue with `leo publish` on Windows
  package/src/root/zip.rs
Labels: bug

#862 [Compiler] Forcing u32 in iterators
  asg/src/statement/iteration.rs
  compiler/tests/statements/iteration_type_fail.leo
  compiler/tests/statements/mod.rs
Labels: bug, feature

#869 bug-fix-852
  asg/src/expression/call.rs
  compiler/tests/circuits/mutable_call_immutable_context.leo
Labels: bug, documentation

#857 [CLI, Feature] Adds username substitution to manifest, improves login and error messages
  .circleci/leo-login-logout.sh
  .circleci/leo-new.sh
  .circleci/r
  leo/api.rs
  leo/commands/init.rs
  leo/commands/new.rs
  leo/commands/package/login.rs
  leo/commands/package/logout.rs
  leo/commands/package/publish.rs
  leo/config.rs
  package/src/lib.rs
  package/src/package.rs
  package/src/root/manifest.rs
  package/tests/initialize/initialize.rs
Labels: bug, feature

#864 [Feature] Removes whitespace in error message
  ast/src/errors/error.rs
  tests/parser/expression/array_init_fail.leo.out
  tests/parser/expression/array_inline_fail.leo.out
  tests/parser/expression/circuit_init_fail.leo.out
  tests/parser/expression/literal/address_fail.leo.out
  tests/parser/expression/literal/group_fail.leo.out
  tests/parser/functions/const_input_fail.leo.out
  tests/parser/functions/input_typed_fail.leo.out
  tests/parser/statement/definition_fail.leo.out
  tests/parser/statement/return_fail.leo.out
Labels: feature

#812 [CI] Adds Pedersen Hash constraints check
  .circleci/config.yml
  .circleci/leo-check-constraints.sh
Labels: ci, feature

#885 [CLI] Allow setting custom API endpoint in ENV
  leo/api.rs
  leo/commands/package/publish.rs
  leo/context.rs
  leo/main.rs
  leo/tests/mod.rs
Labels: developer-experience, feature

#883 [CLI] Adds integration tests to Leo CLI + removes --lib legacy
  Cargo.lock
  Cargo.toml
  examples/silly-sudoku/inputs/test_input.in
  leo/commands/build.rs
  leo/commands/init.rs
  leo/commands/new.rs
  leo/commands/setup.rs
  leo/commands/update.rs
  leo/commands/watch.rs
  leo/logger.rs
  leo/main.rs
  leo/tests/mod.rs
  package/src/lib.rs
  package/src/package.rs
  package/src/source/library.rs
  package/src/source/mod.rs
  package/tests/initialize/initialize.rs
Labels: feature

#884 [Compiler] Adds search inputs path in kebab case
  compiler/src/constraints/constraints.rs
  examples/silly-sudoku/inputs/test-input.in
Labels: developer-experience, feature

#896 [CLI] Makes import path relative to program directory
  compiler/src/compiler.rs
  imports/src/parser/import_parser.rs
  leo/main.rs
Labels: bug, developer-experience, feature

#810 [CLI] Adds CompilerOptions flags to Leo CLI
  compiler/src/compiler.rs
  compiler/tests/compiler/mod.rs
  compiler/tests/mod.rs
  leo/commands/build.rs
  leo/commands/package/publish.rs
  leo/commands/prove.rs
  leo/commands/run.rs
  leo/commands/setup.rs
  leo/commands/test.rs
  leo/commands/watch.rs
  leo/main.rs
  leo/tests/mod.rs
Labels: developer-experience, feature, update-docs

#899 [CLI] leo publish now returns better error messages
  leo/api.rs
  leo/commands/package/publish.rs
Labels: developer-experience, feature

#901 [CLI] Adds tests for imports
  leo/main.rs
Labels: feature
