Repository ProvableHQ/leo, pull requests merged in 2021-03, with the labels that each got.

#692 [CLI] Changes compiler error message for console.assert
  compiler/src/errors/console.rs
  leo/commands/setup.rs
Labels: feature

#766 Refactor Div gadget
  compiler/src/value/integer/integer.rs
  gadgets/benches/integer_arithmetic.rs
  gadgets/src/arithmetic/div.rs
  gadgets/src/arithmetic/mod.rs
  gadgets/src/signed_integer/arithmetic/div.rs
  gadgets/tests/signed_integer/i128.rs
  gadgets/tests/signed_integer/i16.rs
  gadgets/tests/signed_integer/i32.rs
  gadgets/tests/signed_integer/i64.rs
  gadgets/tests/signed_integer/i8.rs
Labels: refactor

#768 Refactor Neg gadget
  compiler/src/value/integer/integer.rs
  gadgets/src/arithmetic/mod.rs
  gadgets/src/arithmetic/neg.rs
  gadgets/src/signed_integer/arithmetic/div.rs
  gadgets/src/signed_integer/arithmetic/neg.rs
  gadgets/src/signed_integer/arithmetic/sub.rs
  gadgets/tests/signed_integer/i128.rs
  gadgets/tests/signed_integer/i16.rs
  gadgets/tests/signed_integer/i32.rs
  gadgets/tests/signed_integer/i64.rs
  gadgets/tests/signed_integer/i8.rs
Labels: refactor

#769 Refactor Pow gadget
  compiler/src/value/integer/integer.rs
  gadgets/src/arithmetic/mod.rs
  gadgets/src/arithmetic/pow.rs
  gadgets/src/signed_integer/arithmetic/pow.rs
  gadgets/tests/signed_integer/i128.rs
  gadgets/tests/signed_integer/i16.rs
  gadgets/tests/signed_integer/i32.rs
  gadgets/tests/signed_integer/i64.rs
  gadgets/tests/signed_integer/i8.rs
Labels: refactor

#770 Refactor Sub gadget
  compiler/src/value/integer/integer.rs
  gadgets/benches/integer_arithmetic.rs
  gadgets/src/arithmetic/mod.rs
  gadgets/src/arithmetic/sub.rs
  gadgets/src/lib.rs
  gadgets/src/signed_integer/arithmetic/div.rs
  gadgets/src/signed_integer/arithmetic/sub.rs
  gadgets/tests/signed_integer/i128.rs
  gadgets/tests/signed_integer/i16.rs
  gadgets/tests/signed_integer/i32.rs
  gadgets/tests/signed_integer/i64.rs
  gadgets/tests/signed_integer/i8.rs
Labels: refactor

#771 Refactor Comparator gadgets
  compiler/src/expression/relational/ge.rs
  compiler/src/expression/relational/gt.rs
  compiler/src/expression/relational/le.rs
  compiler/src/expression/relational/lt.rs
  compiler/src/value/integer/integer.rs
  gadgets/src/bits/comparator.rs
  gadgets/src/bits/mod.rs
  gadgets/src/signed_integer/arithmetic/div.rs
  gadgets/src/signed_integer/relational/cmp.rs
Labels: refactor

#773 Refactor sign extend gadget
  compiler/src/expression/relational/ge.rs
  compiler/src/expression/relational/gt.rs
  compiler/src/expression/relational/le.rs
  compiler/src/expression/relational/lt.rs
  compiler/src/value/integer/integer.rs
  examples/pedersen-hash/src/main.leo
  gadgets/benches/integer_arithmetic.rs
  gadgets/src/arithmetic/add.rs
  gadgets/src/arithmetic/div.rs
  gadgets/src/arithmetic/mod.rs
  gadgets/src/arithmetic/mul.rs
  gadgets/src/arithmetic/neg.rs
  gadgets/src/arithmetic/pow.rs
  gadgets/src/arithmetic/sub.rs
  gadgets/src/bits/comparator.rs
  gadgets/src/bits/mod.rs
  gadgets/src/bits/sign_extend.rs
  gadgets/src/lib.rs
  gadgets/src/signed_integer/arithmetic/add.rs
  gadgets/src/signed_integer/arithmetic/div.rs
  gadgets/src/signed_integer/arithmetic/mul.rs
  gadgets/src/signed_integer/arithmetic/neg.rs
  gadgets/src/signed_integer/arithmetic/pow.rs
  gadgets/src/signed_integer/arithmetic/sub.rs
  gadgets/src/signed_integer/relational/cmp.rs
  gadgets/tests/signed_integer/i128.rs
  gadgets/tests/signed_integer/i16.rs
  gadgets/tests/signed_integer/i32.rs
  gadgets/tests/signed_integer/i64.rs
  gadgets/tests/signed_integer/i8.rs
Labels: refactor

#775 Refactor Int gadgets
  Cargo.lock
  Cargo.toml
  compiler/Cargo.toml
  compiler/src/errors/value/integer.rs
  compiler/src/value/integer/integer.rs
  compiler/src/value/integer/macros.rs
  gadgets/Cargo.toml
  gadgets/LICENSE.md
  gadgets/README.md
  gadgets/benches/integer_arithmetic.rs
  gadgets/src/bits/adder.rs
  gadgets/src/bits/mod.rs
  gadgets/src/bits/rca.rs
  gadgets/src/errors/mod.rs
  gadgets/src/errors/signed_integer.rs
  gadgets/src/lib.rs
  gadgets/src/signed_integer/arithmetic/add.rs
  gadgets/src/signed_integer/arithmetic/div.rs
  gadgets/src/signed_integer/arithmetic/mod.rs
  gadgets/src/signed_integer/arithmetic/mul.rs
  gadgets/src/signed_integer/arithmetic/neg.rs
  gadgets/src/signed_integer/arithmetic/pow.rs
  gadgets/src/signed_integer/arithmetic/sub.rs
  gadgets/src/signed_integer/int_impl.rs
  gadgets/src/signed_integer/mod.rs
  gadgets/src/signed_integer/relational/cmp.rs
  gadgets/src/signed_integer/relational/eq.rs
  gadgets/src/signed_integer/relational/mod.rs
  gadgets/src/signed_integer/utilities/alloc.rs
  gadgets/src/signed_integer/utilities/eq.rs
  gadgets/src/signed_integer/utilities/mod.rs
  gadgets/src/signed_integer/utilities/select.rs
  gadgets/tests/mod.rs
  gadgets/tests/signed_integer/i128.rs
  gadgets/tests/signed_integer/i16.rs
  gadgets/tests/signed_integer/i32.rs
  gadgets/tests/signed_integer/i64.rs
  gadgets/tests/signed_integer/i8.rs
  gadgets/tests/signed_integer/mod.rs
Labels: refactor

#798 Runtime array indexing
  asg/src/error/mod.rs
  asg/src/expression/array_access.rs
  asg/src/expression/array_range_access.rs
  asg/src/reducer/reconstructing_reducer.rs
  compiler/src/errors/expression.rs
  compiler/src/errors/statement.rs
  compiler/src/expression/array/access.rs
  compiler/src/expression/array/index.rs
  compiler/src/expression/binary/binary.rs
  compiler/src/expression/expression.rs
  compiler/src/expression/tuple/access.rs
  compiler/src/function/mut_target.rs
  compiler/src/statement/assign/assignee.rs
  compiler/src/statement/iteration/iteration.rs
  compiler/src/statement/statement.rs
  compiler/src/value/integer/integer.rs
  compiler/tests/array/mod.rs
  compiler/tests/function/array_params_direct_call.leo
  examples/silly-sudoku/.gitignore
  examples/silly-sudoku/Leo.toml
  examples/silly-sudoku/README.md
  examples/silly-sudoku/inputs/silly-sudoku.in
  examples/silly-sudoku/inputs/silly-sudoku.state
  examples/silly-sudoku/src/lib.leo
  examples/silly-sudoku/src/main.leo
Labels: documentation, feature, update-docs

#808 Adds 'leo-abnf' binary package for markdown conversion
  Cargo.lock
  Cargo.toml
  grammar/Cargo.toml
  grammar/src/main.rs
Labels: abnf, feature

#799 initial commit, so I can open retroactive pr
  Cargo.lock
  Cargo.toml
  grammar/.gitattributes
  grammar/Cargo.toml
  grammar/abnf-grammar.md
  grammar/abnf-grammar.txt
  grammar/src/main.rs
  parser/src/errors/syntax.rs
  parser/src/parser/context.rs
  parser/src/parser/expression.rs
  parser/src/parser/file.rs
  parser/src/parser/statement.rs
  parser/src/tokenizer/lexer.rs
  parser/src/tokenizer/mod.rs
  parser/src/tokenizer/token.rs
Labels: abnf
