Repository ProvableHQ/leo, pull requests merged in 2021-06, with the labels that each got.

#996 [Bug] More strict rule for unicode escapes in char and string
  compiler/src/value/char/char.rs
  parser/src/tokenizer/lexer.rs
  tests/expectations/compiler/compiler/char/circuit.leo.out
  tests/expectations/parser/parser/expression/literal/char_fail.leo.out
  tests/parser/expression/literal/char_fail.leo
Labels: bug

#1039 [Feature] Add M1 build, keep target-cpu=native only for MacOS builds
  .cargo/config
  .github/workflows/release.yml
Labels: feature

#1043 canonicalization fixes
  ast/src/reducer/canonicalization.rs
  compiler/tests/canonicalization/big_self_in_circuit_replacement.json
  compiler/tests/canonicalization/big_self_in_circuit_replacement.leo
  compiler/tests/canonicalization/string_transformation.json
  compiler/tests/canonicalization/string_transformation.leo
  tests/compiler/string/equality.leo
Labels: bug-fix

#1054 input bugs fixes
  ast/src/input/input_value.rs
  compiler/src/errors/value/integer.rs
  compiler/src/function/main_function.rs
  compiler/src/value/integer/integer.rs
  compiler/src/value/integer/macros.rs
  input/src/errors/parser.rs
  tests/compiler/input_files/program_input/const_different_types_fail_signed.leo
  tests/compiler/input_files/program_input/const_different_types_fail_unsigned.leo
  tests/compiler/input_files/program_input/different_types_fail_signed.leo
  tests/compiler/input_files/program_input/different_types_fail_unsigned.leo
  tests/compiler/input_files/program_input/input/different_types_fail_const_signedin
  tests/compiler/input_files/program_input/input/different_types_fail_signed.in
  tests/compiler/input_files/program_input/input/different_types_unsigned_const_fail.in
  tests/compiler/input_files/program_input/input/different_types_unsigned_fail.in
  tests/compiler/input_files/program_input/input/var_in_both_sections_fail.in
  tests/compiler/input_files/program_registers/input/array.in
  tests/compiler/integers/u128/negative_input_fail.leo
  tests/compiler/integers/u16/negative_input_fail.leo
  tests/compiler/integers/u32/negative_input_fail.leo
  tests/compiler/integers/u64/negative_input_fail.leo
  tests/compiler/integers/u8/negative_input_fail.leo
  tests/expectations/compiler/compiler/input_files/program_input/const_different_types_fail_signed.leo.out
  tests/expectations/compiler/compiler/input_files/program_input/const_different_types_fail_unsigned.leo.out
  tests/expectations/compiler/compiler/input_files/program_input/different_types_fail.leo.out
  tests/expectations/compiler/compiler/input_files/program_input/different_types_fail_signed.leo.out
  tests/expectations/compiler/compiler/input_files/program_input/different_types_fail_unsigned.leo.out
  tests/expectations/compiler/compiler/input_files/program_input/main_array_fail.leo.out
  tests/expectations/compiler/compiler/input_files/program_input/main_tuple_fail.leo.out
  tests/expectations/compiler/compiler/input_files/program_input_constants/main_array_fail.leo.out
  tests/expectations/compiler/compiler/input_files/program_input_constants/main_tuple_fail.leo.out
  tests/expectations/compiler/compiler/integers/u128/negative_input_fail.leo.out
  tests/expectations/compiler/compiler/integers/u16/negative_input_fail.leo.out
  tests/expectations/compiler/compiler/integers/u32/negative_input_fail.leo.out
  tests/expectations/compiler/compiler/integers/u64/negative_input_fail.leo.out
  tests/expectations/compiler/compiler/integers/u8/negative_input_fail.leo.out
Labels: bug-fix

#1055 [WIP] Import Stabilization RFC
  docs/rfc/003-imports-stabilization.md
Labels: RFC

#1059 Fixes tuple access
  asg/src/error/mod.rs
  asg/src/expression/tuple_init.rs
  tests/compiler/tuples/access.leo
  tests/expectations/compiler/compiler/tuples/access.leo.out
Labels: bug-fix

#1060 array type inference bugs
  asg/src/expression/array_inline.rs
  compiler/tests/type_inference/basic.json
  compiler/tests/type_inference/basic.leo
  tests/compiler/array/spread.leo
  tests/expectations/compiler/compiler/array/spread.leo.out
Labels: bug-fix

#1073 Update to snarkvm 0.6.0
  .circleci/config.yml
  Cargo.lock
  Cargo.toml
  compiler/Cargo.toml
  compiler/src/value/group/targets/edwards_bls12.rs
  state/Cargo.toml
  synthesizer/Cargo.toml
Labels: dependencies

#1074 Bug-Fix: Canonicalization, Array Init, Array Indexing
  asg/src/expression/array_init.rs
  ast/src/reducer/canonicalization.rs
  compiler/src/statement/assign/assignee/array_index.rs
  compiler/src/statement/assign/assignee/array_range_index.rs
  compiler/src/statement/assign/assignee/mod.rs
  compiler/tests/canonicalization/compound_assignment.json
  compiler/tests/canonicalization/compound_assignment.leo
  compiler/tests/canonicalization/string_transformation.json
  compiler/tests/canonicalization/string_transformation.leo
  leo/main.rs
  tests/compiler/array/complex_access.leo
  tests/compiler/array/input/complex_access.in
  tests/compiler/array/ternary_in_array.leo
  tests/expectations/compiler/compiler/array/complex_access.leo.out
  tests/expectations/compiler/compiler/array/ternary_in_array.leo.out
  tests/expectations/compiler/compiler/mutability/array_dyn_mut.leo.out
Labels: bug-fix, update-docs
