Repository ProvableHQ/leo, pull requests merged in 2021-02, with the labels that each got.

#589 [CLI] Adds --skip-key-check option to setup, run and prove commands
  .github/workflows/leo-setup.yml
  leo/commands/prove.rs
  leo/commands/run.rs
  leo/commands/setup.rs
Labels: feature, help wanted

#619 [Feature] Implicit groups
  asg/src/expression/constant.rs
  asg/tests/pass/group/mod.rs
Labels: feature

#617 [Feature] Const Function Arguments
  asg/src/expression/call.rs
  asg/src/expression/variable_ref.rs
  asg/src/input.rs
  asg/src/program/function.rs
  asg/src/statement/assign.rs
  asg/src/statement/definition.rs
  asg/src/statement/iteration.rs
  asg/src/type_.rs
  asg/src/variable.rs
  asg/tests/pass/function/mod.rs
  asg/tests/pass/mutability/mod.rs
  asg/tests/pass/mutability/swap.leo
  ast/src/functions/input/function_input.rs
  compiler/src/function/function.rs
  compiler/src/function/main_function.rs
  compiler/tests/mutability/mod.rs
  compiler/tests/mutability/swap.leo
  grammar/src/functions/input/function_input.rs
  grammar/src/leo.pest
Labels: feature

#638 bug/563-array-input-wrong-dimensions
  ast/src/input/input_value.rs
  compiler/tests/input_files/program_input/input/main_multi_dimension_array.in
  compiler/tests/input_files/program_input/main_multi_dimension_array.leo
  compiler/tests/input_files/program_input/mod.rs
Labels: bug

#654 Fix field/group addition
  asg/src/expression/binary.rs
  asg/tests/pass/field/mod.rs
  asg/tests/pass/group/mod.rs
Labels: bug

#656 [Dependencies] bump snarkvm module versions to 0.0.4
  Cargo.lock
  Cargo.toml
  compiler/Cargo.toml
  gadgets/Cargo.toml
  state/Cargo.toml
Labels: dependencies

#655 Fix circuit resolution
  asg/src/scope.rs
  asg/tests/pass/circuits/mod.rs
Labels: bug, fuzz-bug

#653 Fix return type error for input-dependent branches
  compiler/src/function/result/result.rs
Labels: bug, fuzz-bug

#669 [CLI] Ignore non-input/state files in inputs folder when running tests
  package/src/inputs/pairs.rs
Labels: bug, feature

#670 feature_626/negative-group-contstraints
  compiler/src/value/group/targets/edwards_bls12.rs
  compiler/tests/group/mod.rs
  compiler/tests/group/positive_and_negative.leo
Labels: bug

#675 add contributing.md
  CONTRIBUTING.md
Labels: developer-experience, documentation
