Repository ProvableHQ/leo, pull requests merged in 2021-09, with the labels that each got.

#1313 [Implementation] Arrays without size
  asg/src/expression/array_access.rs
  asg/src/expression/array_inline.rs
  asg/src/scope.rs
  asg/src/type_.rs
  ast-passes/src/canonicalization/canonicalizer.rs
  ast/src/types/type_.rs
  compiler/src/phases/reducing_director.rs
  errors/src/parser/parser_errors.rs
  grammar/abnf-grammar.txt
  parser/src/parser/expression.rs
  parser/src/parser/type_.rs
  tests/compiler/aliases/fn_return.leo
  tests/compiler/array_without_size/definition.leo
  tests/compiler/array_without_size/function_input.leo
  tests/compiler/array_without_size/input/dummy.in
  tests/compiler/array_without_size/type_alias.leo
  tests/expectations/compiler/compiler/array_without_size/definition.leo.out
  tests/expectations/compiler/compiler/array_without_size/function_input.leo.out
  tests/expectations/compiler/compiler/array_without_size/type_alias.leo.out
Labels: ast, Implementation

#1327 [ABNF] CircuitOrAlias changed to Identifier
  asg/src/scope.rs
  asg/src/type_.rs
  ast-passes/src/canonicalization/canonicalizer.rs
  ast/src/reducer/reconstructing_director.rs
  ast/src/types/type_.rs
  compiler/src/phases/reducing_director.rs
  parser/src/parser/type_.rs
  tests/expectations/compiler/compiler/aliases/arith.leo.out
  tests/expectations/compiler/compiler/aliases/basic.leo.out
  tests/expectations/compiler/compiler/aliases/circuit.leo.out
  tests/expectations/compiler/compiler/aliases/fn_return.leo.out
  tests/expectations/compiler/compiler/aliases/shadowing_arg.leo.out
  tests/expectations/compiler/compiler/aliases/shadowing_arg_fail.leo.out
  tests/expectations/compiler/compiler/aliases/shadowing_var_allowed.leo.out
  tests/expectations/compiler/compiler/aliases/shadowing_var_fail.leo.out
  tests/expectations/compiler/compiler/array/complex_access.leo.out
  tests/expectations/compiler/compiler/array/registers.leo.out
  tests/expectations/compiler/compiler/char/circuit.leo.out
  tests/expectations/compiler/compiler/circuits/big_self_in_circuit_replacement.leo.out
  tests/expectations/compiler/compiler/circuits/const_self_variable.leo.out
  tests/expectations/compiler/compiler/circuits/define_circuit_inside_circuit_function.leo.out
  tests/expectations/compiler/compiler/circuits/duplicate_name_context.leo.out
  tests/expectations/compiler/compiler/circuits/inline.leo.out
  tests/expectations/compiler/compiler/circuits/inline_member_pass.leo.out
  tests/expectations/compiler/compiler/circuits/member_function.leo.out
  tests/expectations/compiler/compiler/circuits/member_function_nested.leo.out
  tests/expectations/compiler/compiler/circuits/member_variable.leo.out
  tests/expectations/compiler/compiler/circuits/member_variable_and_function.leo.out
  tests/expectations/compiler/compiler/circuits/mut_self_variable.leo.out
  tests/expectations/compiler/compiler/circuits/mut_self_variable_branch.leo.out
  tests/expectations/compiler/compiler/circuits/mut_self_variable_conditional.leo.out
  tests/expectations/compiler/compiler/circuits/mut_variable.leo.out
  tests/expectations/compiler/compiler/circuits/mutable_call_immutable_context.leo.out
  tests/expectations/compiler/compiler/circuits/pedersen_mock.leo.out
  tests/expectations/compiler/compiler/circuits/return_self_type_array.leo.out
  tests/expectations/compiler/compiler/circuits/return_self_type_tuple.leo.out
  tests/expectations/compiler/compiler/circuits/self_member.leo.out
  tests/expectations/compiler/compiler/console/debug.leo.out
  tests/expectations/compiler/compiler/function/multiple_returns_main.leo.out
  tests/expectations/compiler/compiler/global_consts/global_const_types.leo.out
  tests/expectations/compiler/compiler/import_local/import_all.leo.out
  tests/expectations/compiler/compiler/import_local/import_many.leo.out
  tests/expectations/compiler/compiler/input_files/program_input/const_different_types_fail_signed.leo.out
  tests/expectations/compiler/compiler/input_files/program_input/const_different_types_fail_unsigned.leo.out
  tests/expectations/compiler/compiler/input_files/program_input/different_types_fail.leo.out
  tests/expectations/compiler/compiler/input_files/program_input/different_types_fail_unsigned.leo.out
  tests/expectations/compiler/compiler/input_files/program_input_and_program_state/basic.leo.out
  tests/expectations/compiler/compiler/input_files/program_input_and_program_state/token_withdraw.leo.out
  tests/expectations/compiler/compiler/input_files/program_state/access_all.leo.out
  tests/expectations/compiler/compiler/input_files/program_state/access_state.leo.out
  tests/expectations/compiler/compiler/mutability/circuit_function_mut.leo.out
  tests/expectations/compiler/compiler/mutability/circuit_variable_mut.leo.out
  tests/expectations/compiler/compiler/statements/compound_assignment.leo.out
  tests/expectations/compiler/compiler/statements/reverse_loop.leo.out
  tests/expectations/compiler/compiler/string/circuit.leo.out
  tests/expectations/parser/parser/expression/cast.leo.out
  tests/expectations/parser/parser/functions/param_circuit.leo.out
Labels: ast

#1296 [Bugfix] Big Self Canonicalization Fixes
  ast-passes/src/canonicalization/canonicalizer.rs
  tests/compiler/circuits/big_self_in_circuit_replacement.leo
  tests/expectations/compiler/compiler/circuits/big_self_in_circuit_replacement.leo.out
Labels: bug-fix

#1329 [Bug] Fix ordering in unexpected_type error
  asg/src/expression/array_init.rs
  asg/src/expression/array_inline.rs
  asg/src/expression/array_range_access.rs
  asg/src/expression/binary.rs
  asg/src/expression/circuit_access.rs
  asg/src/expression/tuple_access.rs
  asg/src/expression/unary.rs
  errors/src/asg/asg_errors.rs
Labels: bug-fix

#1321 [CI] Change ACL2 to manual trigger
  .github/workflows/acl2.yml
Labels: ci

#1332 [RFC] Update RFC #8
  docs/rfc/008-built-in-declarations.md
Labels: RFC

#1334 [Bugfix] proper canoncialization of function inputs
  ast-passes/src/canonicalization/canonicalizer.rs
  tests/compiler/circuits/big_self_in_circuit_replacement.leo
  tests/expectations/compiler/compiler/circuits/big_self_in_circuit_replacement.leo.out
Labels: bug-fix

#1349 [tgc CI] make log more readable; allow tgc type inference to run even…
  .github/workflows/acl2.yml
  tests/expectations/compiler/compiler/array_without_size/length.leo.out
  tests/expectations/compiler/compiler/array_without_size/length_fail.leo.out
  tests/expectations/compiler/compiler/array_without_size/length_function.leo.out
Labels: ci

#1369 [Fix] Throw an error when comparing arrays of different lengths
  compiler/src/expression/relational/eq.rs
  errors/src/compiler/compiler_errors.rs
  tests/compiler/array_without_size/compare_fail.leo
  tests/expectations/compiler/compiler/array_without_size/compare_fail.leo.out
Labels: bug-fix

#1348 [Implementation] WASM for Leo
  .github/workflows/wasm.yml
  Cargo.lock
  Cargo.toml
  errors/src/common/backtraced.rs
  errors/src/common/formatted.rs
  errors/src/common/macros.rs
  errors/src/common/traits.rs
  errors/src/compiler/compiler_errors.rs
  errors/src/lib.rs
  leo/tests/mod.rs
  wasm/.gitignore
  wasm/Cargo.toml
  wasm/README.md
  wasm/src/lib.rs
  wasm/tests/.gitignore
  wasm/tests/package-lock.json
  wasm/tests/package.json
  wasm/tests/src/index.ts
  wasm/tests/tsconfig.json
Labels: Implementation, ci
